apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    nginx.ingress.kubernetes.io/rewrite-target: / 
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  rules:
  - host: "www.533267306573.realhandsonlabs.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        frontend:
          service:
            name: myapp-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: myapp-backend
            port:
              number: 80
