apiVersion: v1
kind: Service
metadata:
  name: myapp-frontend
  namespace: argocd
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: myapp-frontend
